#!/bin/sh

# Comments to support chkconfig on RedHat Linux
# chkconfig: 2345 64 36

### BEGIN INIT INFO
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Start npm
case $1 in
	start )
		cd /data/npm.fe.yeshj.com
		sudo -u tomcat /home/soft/node/bin/npm run start
		;;
	stop )
		cd /data/npm.fe.yeshj.com
		sudo -u tomcat /home/soft/node/bin/npm run stop
		;;
	status )
		cd /data/npm.fe.yeshj.com
		sudo -u tomcat /home/soft/node/bin/npm run status
		;;
	* )
		echo "Use {start|stop|status}"
		;;
esac
