#!/bin/sh

# Comments to support chkconfig on RedHat Linux
# chkconfig: 2345 64 36

### BEGIN INIT INFO
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

DAEMON=rsync
CONFIG_NAME=rsyncd.conf
DATA_DIR=/home/soft/rsync


case $1 in
	start )
		echo "Starting Rsync Server....."
		$DAEMON --daemon --config=$DATA_DIR/etc/$CONFIG_NAME
		if [[ $? -eq 0 ]];then
			echo "Starting Rsync Server Successfully"
		fi
		;;
	stop )
		echo "Stopping Rsync Server....."
		kill -9 `ps -ef | grep rsync | grep rsyncd.conf | grep -v grep | awk '{print $2}'`
		rm -rf $DATA_DIR/log/$DAEMON\.pid
		echo "Stoppping Rsync Server Successfully"
		;;
	status )
		pid=`ps -ef | grep rsync | grep rsyncd.conf | grep -v grep | awk '{print $2}'`
		if [[ $pid -gt 0 ]];then
			echo "Rsync Server Running"
		fi
		;;
	restart )
		kill -9 `ps -ef | grep rsync | grep rsyncd.conf | grep -v grep | awk '{print $2}'`
		rm -rf $DATA_DIR/log/$DAEMON\.pid
		$DAEMON --daemon --config=$DATA_DIR/etc/$CONFIG_NAME
                pid=`ps -ef | grep rsync | grep rsyncd.conf | grep -v grep | awk '{print $2}'`
                if [[ $pid -gt 0 ]];then
                        echo "Rsync Server Restarting Successfully"
                fi
		;;
	* )
		echo "Use {start|stop|status|restart}"
		;;
esac
